apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: shib
  spec:
    replicas: 1
    selector:
      deploymentconfig: shib
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: shib
      spec:
        containers:
        - image: 721685138178.dkr.ecr.eu-west-1.amazonaws.com/worth/shibboleth:1.0-SNAPSHOT
          name: shib
          ports:
          - containerPort: 443
          - containerPort: 389
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: shib
  spec:
    ports:
    - name: 389-tcp
      port: 389
      targetPort: 389
    - name: 443-tcp
      port: 443
      targetPort: 443
    selector:
      deploymentconfig: shib
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: shib
  spec:
    host: ifs-local-dev
    port:
      targetPort: 443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: shib
