version: '2'
services:
  hub:
    container_name: hub
    image: selenium/hub
    environment:
      - GRID_BROWSER_TIMEOUT=90000
      - GRID_TIMEOUT=100000
    ports:
      - '4444:4444'
      - '3000:3000'
    networks:
      selenium-network:
        aliases:
          - hub
  chrome:
    build:
      context: .
      dockerfile: chrome-dockerfile
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '5900'
    links:
      - "hub:hub"
    external_links:
      - ifs-local-dev
    depends_on:
      - hub
    networks:
      - selenium-network
      - ifs_front-tier
networks:
  selenium-network:
    driver: bridge
  ifs_front-tier:
    external: true
