version: '2'
services:
  hub:
    container_name: hub
    image: selenium/standalone-chrome:3.0.1-dysprosium
    environment:
      - NODE_MAX_SESSION=20
      - NODE_MAX_INSTANCES=20
      - NODE_REGISTER_CYCLE=600
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '4444:4444'
      - '3000:3000'
    networks:
      selenium-network:
        aliases:
          - hub
    networks:
      - innovationfundingservice_ifs
networks:
  selenium-network:
    driver: bridge
  innovationfundingservice_ifs:
    external: true
