version: '3'
services:

  application-svc:
    links:
      - admin
      - zipkin

  assessment-svc:
    links:
      - admin
      - zipkin


  competition-mgt-svc:
    links:
      - admin
      - zipkin

  project-setup-mgt-svc:
    links:
      - admin
      - zipkin

  project-setup-svc:
    links:
      - admin
      - zipkin
  front-door-svc:
    links:
      - admin
      - zipkin

  data-service:
    links:
      - admin
      - zipkin
  admin:
    hostname: admin
    image: enmobile/docker-spring-boot-admin
    ports:
    - "3001:8123"
    networks:
      - ifs
  zipkin:
    hostname: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - ifs
