version: '2'
services:
  shib:
    build:
      context: setup-files/scripts/docker/shibboleth
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    ports:
      - "443:443"
      - "389:389"
    links:
      - application-service
      - assessment-service
      - competition-mgt-service
      - project-setup-mgt-service
      - project-setup-service
    networks:
      - ifs

  application-service:
    image: worth/application-service:1.0-SNAPSHOT
    links:
      - data:data-service
      - admin
    ports:
      - "8081:8080"
    networks:
      - ifs
    

  assessment-service:
    image: worth/assessment-service:1.0-SNAPSHOT
    links:
      - data:data-service
      - admin
    ports:
      - "8082:8080"
    networks:
      - ifs

  competition-mgt-service:
    image: worth/competition-management-service:1.0-SNAPSHOT
    links:
      - data:data-service
      - admin
    ports:
      - "8083:8080"
    networks:
      - ifs

  project-setup-mgt-service:
    image: worth/project-setup-management-service:1.0-SNAPSHOT
    links:
      - data:data-service
      - admin
    ports:
      - "8084:8080"
    networks:
      - ifs

  project-setup-service:
    image: worth/project-setup-service:1.0-SNAPSHOT
    links:
      - data:data-service
      - admin
    ports:
      - "8085:8080"
    networks:
      - ifs

  data:
    image: worth/data-service:1.0-SNAPSHOT
    volumes:
      - ./robot-tests/upload_files/:/tmp/ifs-local
    links:
      - mysql:ifs-database
      - admin
      - smtp
    ports:
      - "8090:8080"
    networks:
      - ifs

  mysql:
    image: mysql:5.5.49
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ifs
    restart: on-failure
    networks:
      - ifs

  smtp:
    image: camptocamp/smtp-sink
    expose:
      - 25
    networks:
      - ifs

  imap:
    image: camptocamp/courier-imap
    volumes_from:
      - smtp:rw
    expose:
      - 143
    ports:
      - "9876:143"
    networks:
      - ifs

  webmail:
    image: camptocamp/sqwebmail
    ports:
      - "1234:80"
    links:
      - smtp
      - imap
    volumes_from:
      - smtp:rw
    networks:
      - ifs

  admin:
    image: enmobile/docker-spring-boot-admin
    ports:
    - "3001:8123"
    networks:
      - ifs
networks:
  ifs:
    driver: bridge
