version: '3'
services:

  registration-svc:
    hostname: registration-svc
    ports:
      - "8088:8080"
      - "9008:8000"
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n

  application-svc:
    hostname: application-svc
    ports:
      - "8081:8080"
      - "9001:8000"
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n

  assessment-svc:
    hostname: assessment-svc
    ports:
      - "8082:8080"
      - "9002:8000"
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n


  competition-mgt-svc:
    hostname: competition-mgt-svc
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n
    ports:
      - "8083:8080"
      - "9003:8000"

  project-setup-mgt-svc:
    hostname: project-setup-mgt-svc
    ports:
      - "8084:8080"
      - "9004:8000"
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n

  project-setup-svc:
    hostname: project-setup-svc
    ports:
      - "8085:8080"
      - "9005:8000"
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n
  front-door-svc:
    hostname: front-door-svc
    ports:
      - "8087:8080"
      - "9007:8000"
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n

  data-service:
    hostname: data-service
    links:
      - mail
      - mysql:ifs-database
    volumes:
      - ./robot-tests/upload_files/:/tmp/ifs-local
    ports:
      - "8086:8080"
      - "9006:8000"
    environment:
      - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n

  mail:
    image: davidrums/local-webmail-sink
    ports:
      - "9876:8143"
      - "8765:8080"
    networks:
      - ifs

  mysql:
    image: mysql:5.5.49
    ports:
      - "3306:3306"
    command: [--character-set-server=utf8, --collation-server=utf8_bin]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ifs
    restart: on-failure
    networks:
      - ifs