version: '2'
services:

  shib:
    container_name: ifs-local-dev
    image: g2g3/ifs-local-dev
    ports:
      - "443:443"
      - "389:389"
    links:
      - web
      - data
    networks:
      front-tier:
        aliases:
         - iuk-auth-localdev

  web:
    container_name: ifs-web-service
    build:
      context: .
      dockerfile: web-dockerfile
    ports:
      - "8080:8080"
      - "12345:12345"
    links:
      - data
    networks:
      front-tier:
        aliases:
          - ifs-web-service
          - ifs-application-host

  data:
    container_name: ifs-data-service
    build:
      context: .
      dockerfile: data-dockerfile
    ports:
      - "8090:8080"
      - "12346:12345"
    depends_on:
      - mysql
    networks:
      front-tier:
        aliases:
          - data-service
      back-tier:
        aliases:
          - data-service

  mysql:
    container_name: ifs-database
    image: mysql:5.5.49
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ifs
    restart: on-failure
    networks:
      back-tier:
        aliases:
         - database
         - ifs-database

  smtp:
    container_name: smtp
    image: camptocamp/smtp-sink
    expose:
      - 25
    networks:
      - back-tier

  imap:
    container_name: imap
    image: camptocamp/courier-imap
    volumes_from:
      - smtp:rw
    expose:
      - 143
    networks:
      - front-tier
      - back-tier

  webmail:
    container_name: webmail
    image: camptocamp/sqwebmail
    ports:
      - "1234:80"
    volumes_from:
      - smtp:rw
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge