version: '2'
services:
  shib:
    build:
      context: setup-files/scripts/docker/shibboleth
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    ports:
      - "443:443"
      - "389:389"
    links:
      - application-service
      - assessment-service
      - competition-mgt-service
      - project-setup-mgt-service
      - project-setup-service
    networks:
      ifs:
        aliases:
          - iuk-auth-localdev

  application-service:
    image: worth/application-service:1.0-SNAPSHOT
    links:
      - data:data-service
    networks:
      - ifs
    

  assessment-service:
    image: worth/assessment-service:1.0-SNAPSHOT
    links:
      - data:data-service
    networks:
      - ifs

  competition-mgt-service:
    image: worth/competition-management-service:1.0-SNAPSHOT
    links:
      - data:data-service
    networks:
      - ifs

  project-setup-mgt-service:
    image: worth/project-setup-management-service:1.0-SNAPSHOT
    links:
      - data:data-service
    networks:
      - ifs

  project-setup-service:
    image: worth/project-setup-service:1.0-SNAPSHOT
    links:
      - data:data-service
    networks:
      - ifs

  data:
    image: worth/data-service:1.0-SNAPSHOT

    links:
      - mysql:ifs-database
    networks:
      ifs:
        aliases:
          - ifs-data-service

  mysql:
    image: mysql:5.5.49
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ifs
    restart: on-failure
    networks:
      - ifs
networks:
  ifs:
    driver: bridge
