version: '2'
services:
  shib:
    image: innovateuk/shibboleth:1.0-SNAPSHOT
    cap_add:
      - SYS_PTRACE
    ports:
      - "443:443"
      - "389:389"
    networks:
      ifs:
        aliases:
          - iuk-auth-localdev

  application-service:
    image: worth/application-service:1.0-SNAPSHOT
    networks:
      - ifs
    

  assessment-service:
    image: worth/assessment-service:1.0-SNAPSHOT
    networks:
      - ifs

  competition-mgt-service:
    image: worth/competition-management-service:1.0-SNAPSHOT
    networks:
      - ifs

  project-setup-mgt-service:
    image: worth/project-setup-management-service:1.0-SNAPSHOT
    networks:
      - ifs

  project-setup-service:
    image: worth/project-setup-service:1.0-SNAPSHOT
    networks:
      - ifs

  data-service:
    image: worth/data-service:1.0-SNAPSHOT
    networks:
      ifs:
        aliases:
          - ifs-data-service

networks:
  ifs:
    driver: bridge
