apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.0.0.64
    ports:
      - port: 1
  - addresses:
      - ip: 10.0.0.31
    ports:
      - port: 1