apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: mail
  spec:
    replicas: 1
    selector:
      deploymentconfig: mail
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: mail
      spec:
        containers:
        - image: davidrums/local-webmail-sink:preview
          name: mail
          imagePullPolicy: IfNotPresent
          env:
          - name: FQDN
            value: <<MAIL-ADDRESS>>
          ports:
          - containerPort: 8025
          - containerPort: 443
          - containerPort: 8143
          resources:
            requests:
              memory: 50M
            limits:
              memory: 60M
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mail
  spec:
    ports:
    - name: 8025-tcp
      port: 8025
      targetPort: 8025
    - name: 443-tcp
      port: 443
      targetPort: 443
    - name: 8143-tcp
      port: 8143
      targetPort: 8143
    selector:
      deploymentconfig: mail
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: mail
  spec:
    host: <<MAIL-ADDRESS>>
    port:
      targetPort: 443-tcp
    tls:
      termination: passthrough
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: mail
