apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: mail
  spec:
    replicas: 1
    selector:
      deploymentconfig: mail
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: mail
      spec:
        containers:
        - image: davidrums/local-webmail-sink
          name: mail
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8025
          - containerPort: 8080
          - containerPort: 8143
          resources:
            limits:
              memory: 100M
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mail
  spec:
    ports:
    - name: 8025-tcp
      port: 8025
      targetPort: 8025
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    - name: 8143-tcp
      port: 8143
      targetPort: 8143
    selector:
      deploymentconfig: mail
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: mail
  spec:
    host: <<MAIL-ADDRESS>>
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: mail
