apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: imap
  spec:
    replicas: 1
    selector:
      deploymentconfig: imap
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: imap
      spec:
        containers:
        - image: camptocamp/courier-imap
          name: imap
          ports:
          - containerPort: 143
          resources: {}
          volumeMounts:
          - name: smtp-maildir-storage
            mountPath: /home/smtp/Maildir
        - image: camptocamp/smtp-sink
          name: smtp
          ports:
          - containerPort: 25
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    maildirmake test &&
                    mv test/* Maildir/ &&
                    chown -R smtp:smtp Maildir/
          resources: {}
          volumeMounts:
          - name: smtp-maildir-storage
            mountPath: /home/smtp/Maildir
        - image: camptocamp/sqwebmail
          name: webmail
          ports:
          - containerPort: 80
          resources: {}
          volumeMounts:
          - name: smtp-maildir-storage
            mountPath: /home/smtp/Maildir
        volumes:
        - emptyDir: {}
          name: smtp-maildir-storage
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: imap
  spec:
    ports:
    - name: 25-tcp
      port: 25
      targetPort: 25
    - name: 80-tcp
      port: 80
      targetPort: 80
    - name: 143-tcp
      port: 143
      targetPort: 143
    selector:
      deploymentconfig: imap
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: imap
  spec:
    host: imap
    port:
      targetPort: 80-tcp
    to:
      kind: Service
      name: imap