apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: application-svc
  spec:
    replicas: 1
    selector:
      deploymentconfig: application-svc
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: application-svc


      spec:
        containers:
        - image: innovateuk/application-service:1.0-SNAPSHOT
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          name: application-svc
          imagePullPolicy: Always
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"logout":{"url": "https://<<SHIB-ADDRESS>>/Logout/"}}'
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1G
    test: false
    triggers:
    - type: ConfigChange
    status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: application-svc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    - name: 8009-tcp
      port: 8009
      targetPort: 8009
    selector:
      deploymentconfig: application-svc
  status:
    loadBalancer: {}
