apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: competition-mgt-svc
  spec:
    replicas: 1
    selector:
      deploymentconfig: competition-mgt-svc
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 600
        maxSurge: 2
        maxUnavailable: 0
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: competition-mgt-svc
      spec:
        containers:
        - image: innovateuk/competition-management-service:1.0-SNAPSHOT
          name: competition-mgt-svc
          livenessProbe:
            httpGet:
              path: /management/monitoring/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/monitoring/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          imagePullPolicy: Always
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"logout":{"url": "https://<<SHIB-ADDRESS>>/Logout/"}}'
          - name: JAVA_OPTS
            value: -Xms600m -Xmx600m
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1G
    test: false
    triggers:
    - type: ConfigChange
    status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: competition-mgt-svc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    - name: 8009-tcp
      port: 8009
      targetPort: 8009
    selector:
      deploymentconfig: competition-mgt-svc
  status:
    loadBalancer: {}
