apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: project-setup-mgt-svc
  spec:
    replicas: 1
    selector:
      deploymentconfig: project-setup-mgt-svc
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: project-setup-mgt-svc
      spec:
        containers:
        - image: innovateuk/project-setup-management-service:1.0-SNAPSHOT
          name: project-setup-mgt-svc
          ports:
          - containerPort: 8080
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: project-setup-mgt-svc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    - name: 8009-tcp
      port: 8009
      targetPort: 8009
    selector:
      deploymentconfig: project-setup-mgt-svc
  status:
    loadBalancer: {}
