apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: project-setup-mgt-svc
  spec:
    replicas: 1
    selector:
      deploymentconfig: project-setup-mgt-svc
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 600
        maxSurge: 2
        maxUnavailable: 0
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: project-setup-mgt-svc
      spec:
        containers:
        - image: innovateuk/project-setup-management-service:1.0-SNAPSHOT
          name: project-setup-mgt-svc
          livenessProbe:
            httpGet:
              path: /project-setup-management/monitoring/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 31
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /project-setup-management/monitoring/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          imagePullPolicy: Always
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"logout":{"url": "https://<<SHIB-ADDRESS>>/Logout/"}}'
          - name: JAVA_OPTS
            value: -Xms600m -Xmx600m -javaagent:/newrelic.jar
          - name: NEW_RELIC_APP_NAME
            value: "ifs-project-setup-mgt-service"
          - name: NEW_RELIC_LICENSE_KEY
            value: "<<NEWRELIC-LICENCE-KEY>>"
          - name: NEW_RELIC_LOG
            value: "STDOUT"
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1G
              cpu: 1000m
            requests:
              cpu: 400m
    test: false
    triggers:
    - type: ConfigChange
    status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: project-setup-mgt-svc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    - name: 8009-tcp
      port: 8009
      targetPort: 8009
    selector:
      deploymentconfig: project-setup-mgt-svc
  status:
    loadBalancer: {}
