apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: shib
  spec:
    replicas: 1
    selector:
      deploymentconfig: shib
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: shib
      spec:
        containers:
        - image: innovateuk/ifs-shib-sp:0.2.0
          name: shib
          env:
          - name: SPHOST
            value: <<SHIB-ADDRESS>>
          - name: IDPHOST
            value: <<SHIB-IDP-ADDRESS>>
          - name: HTTPSPORT
            value: "9443"
          - name: HTTPPORT
            value: "9080"
          ports:
          - containerPort: 9443
          - containerPort: 9080
          resources: {}
          test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: shib
  spec:
    ports:
    - name: 443-tcp
      port: 443
      targetPort: 9443
    selector:
      deploymentconfig: shib
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: shib
  spec:
    host: <<SHIB-ADDRESS>>
    port:
      targetPort: 443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: shib
