apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ldap
  spec:
    replicas: 1
    selector:
      deploymentconfig: ldap
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: ldap
      spec:
        containers:
        - env:
          - name: LDAPPORT
            value: "8389"
          - name: LDAPSSLPORT
            value: "8636"
          image: 721685138178.dkr.ecr.eu-west-2.amazonaws.com/innovateuk/ifs-ldap:0.2.1
          name: ldap
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8389
          - containerPort: 8636
          resources:
            limits:
              memory: 500M
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: ldap
  spec:
    ports:
    - name: 389-tcp
      port: 389
      targetPort: 8389
    selector:
      deploymentconfig: ldap
  status:
    loadBalancer: {}
