apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: idp
  spec:
    replicas: 1
    selector:
      deploymentconfig: idp
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: idp
      spec:
        containers:
        - image: 721685138178.dkr.ecr.eu-west-2.amazonaws.com/innovateuk/ifs-shib-idp:0.2.0
          name: idp
          imagePullPolicy: IfNotPresent
          env:
          - name: SPHOST
            value: <<SHIB-ADDRESS>>
          - name: IDPHOST
            value: <<SHIB-IDP-ADDRESS>>
          - name: HTTPSPORT
            value: "9443"
          - name: HTTPPORT
            value: "9080"
          ports:
          - containerPort: 9443
          - containerPort: 9080
          resources:
            limits:
              memory: 500M
          test: false
  triggers:
  - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: idp
  spec:
    ports:
    - name: 443-tcp
      port: 443
      targetPort: 9443
    selector:
      deploymentconfig: idp
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Route
  metadata:
    name: idp
  spec:
    host: <<SHIB-IDP-ADDRESS>>
    port:
      targetPort: 443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: idp
