apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: db-config
  data:
    DB_NAME: "<<DB-NAME>>"
    DB_USER: "<<DB-USER>>"
    DB_PASS: "<<DB-PASS>>"
    DB_HOST: "<<DB-HOST>>"
    DB_PORT: "<<DB-PORT>>"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: flyway-config
  data:
    FLYWAY_LOCATIONS: "<<FLYWAY-LOCATIONS>>"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ldap-config
  data:
    LDAP_HOST: "<<LDAP-HOST>>"
    LDAP_PORT: "<<LDAP-PORT>>"
    LDAP_PASS: "<<LDAP-PASS>>"
    LDAP_DOMAIN: "<<LDAP-DOMAIN>>"
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: dbreset
  spec:
    template:
      metadata:
        name: dbreset
      spec:
        containers:
          - name: dbreset
            image: innovateuk/dbreset:1.0-SNAPSHOT
            imagePullPolicy: Always
            command: [ "/bin/bash", "-exec" ]
            args:
            - |
              cat > flyway.conf <<EOF
              flyway.url=jdbc:mysql://${DB_HOST}:${DB_PORT}
              flyway.schemas=$DB_NAME
              flyway.locations=$FLYWAY_LOCATIONS
              flyway.user=$DB_USER
              flyway.password=$DB_PASS
              EOF
              flyway clean
              flyway migrate
              flyway info
              flyway validate
              . /ldap-sync-from-ifs-db.sh
            env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PASS
            - name: LDAP_HOST
              valueFrom:
                configMapKeyRef:
                  name: ldap-config
                  key: LDAP_HOST
            - name: LDAP_PORT
              valueFrom:
                configMapKeyRef:
                  name: ldap-config
                  key: LDAP_PORT
            - name: LDAP_PASS
              valueFrom:
                configMapKeyRef:
                  name: ldap-config
                  key: LDAP_PASS
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ldap-config
                  key: LDAP_DOMAIN
            - name: FLYWAY_LOCATIONS
              valueFrom:
                configMapKeyRef:
                  name: flyway-config
                  key: FLYWAY_LOCATIONS
        restartPolicy: Never
