apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: admin
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: enmobile/docker-spring-boot-admin
      from:
        kind: DockerImage
        name: enmobile/docker-spring-boot-admin
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: admin
  spec:
    replicas: 1
    selector:
      deploymentconfig: admin
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: admin
      spec:
        containers:
        - image: enmobile/docker-spring-boot-admin
          name: admin
          ports:
          - containerPort: 8123
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - admin
        from:
          kind: ImageStreamTag
          name: admin:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: admin
  spec:
    ports:
    - name: 8123-tcp
      port: 8123
      targetPort: 8123
    selector:
      deploymentconfig: admin
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: admin
  spec:
    port:
      targetPort: 8123-tcp
    to:
      kind: Service
      name: admin
