apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: application-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: application-service
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: application-service
      spec:
        containers:
        - image: 721685138178.dkr.ecr.eu-west-1.amazonaws.com/application-service:1.0-SNAPSHOT
          name: application-service
          ports:
          - containerPort: 8080
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: application-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: application-service
  status:
    loadBalancer: {}
