apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: imap
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: camptocamp/courier-imap
      from:
        kind: DockerImage
        name: camptocamp/courier-imap
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: smtp
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: camptocamp/smtp-sink
      from:
        kind: DockerImage
        name: camptocamp/smtp-sink
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: webmail
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: camptocamp/sqwebmail
      from:
        kind: DockerImage
        name: camptocamp/sqwebmail
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: imap
  spec:
    replicas: 1
    selector:
      deploymentconfig: imap
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: imap
      spec:
        containers:
        - image: camptocamp/courier-imap
          name: imap
          ports:
          - containerPort: 143
          resources: {}
        - image: camptocamp/smtp-sink
          name: smtp
          resources: {}
        - image: camptocamp/sqwebmail
          name: webmail
          ports:
          - containerPort: 80
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - imap
        from:
          kind: ImageStreamTag
          name: imap:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - smtp
        from:
          kind: ImageStreamTag
          name: smtp:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - webmail
        from:
          kind: ImageStreamTag
          name: webmail:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: imap
  spec:
    ports:
    - name: 80-tcp
      port: 80
      targetPort: 80
    - name: 143-tcp
      port: 143
      targetPort: 143
    selector:
      deploymentconfig: imap
  status:
    loadBalancer: {}