apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: selenium-grid
  spec:
    replicas: 1
    selector:
      deploymentconfig: selenium-grid
    template:
      metadata:
        labels:
          deploymentconfig: selenium-grid
      spec:
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        containers:
        - image: selenium/standalone-chrome:3.0.1-dysprosium
          name: hub
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          ports:
          - containerPort: 4444
          - containerPort: 3000
          resources:
            limits:
              memory: 3000M
              cpu: 900m
            requests:
              cpu: 400m
              memory: 400M
          env:
          - name: NODE_MAX_SESSION
            value: "20"
          - name: NODE_MAX_INSTANCES
            value: "20"
          - name: NODE_REGISTER_CYCLE
            value: "600"
          - name: DBUS_SESSION_BUS_ADDRESS
            value: "/dev/null"
          - name: SCREEN_WIDTH
            value: "1920"
          - name: SCREEN_HEIGHT
            value: "5000"
          - name: JAVA_OPTS
            value: "-Xms1024m -Xmx1024m"
          - name: POOL_MAX
            description: Max thread count for incoming and outgoing connections
            value: "30000"
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: hub
  spec:
    ports:
    - name: 4444-tcp
      port: 4444
      targetPort: 4444
    selector:
      deploymentconfig: selenium-grid
  status:
    loadBalancer: {}

