apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: selenium-grid
  spec:
    replicas: 1
    selector:
      deploymentconfig: selenium-grid
    template:
      metadata:
        labels:
          deploymentconfig: selenium-grid
      spec:
        containers:
        - image: selenium/hub:3.0.1-dysprosium
          name: hub
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4444
          - containerPort: 3000
          env:
          - name: GRID_BROWSER_TIMEOUT
            value: "90000"
          - name: GRID_TIMEOUT
            value: "100000"
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: chrome
  spec:
    replicas: 2
    selector:
      deploymentconfig: chrome
    template:
      metadata:
        labels:
          deploymentconfig: chrome
      spec:
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        containers:
        - image: selenium/node-chrome-debug:3.0.1-dysprosium
          name: chrome
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    echo "$SHIB_PORT_443_TCP_ADDR <<SHIB-ADDRESS>>" >> /etc/hosts &&
                    echo "$IDP_PORT_443_TCP_ADDR auth-<<SHIB-ADDRESS>>" >> /etc/hosts
          ports:
          - containerPort: 5900
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          env:
          - name: NODE_MAX_SESSION
            value: "20"
          - name: NODE_MAX_INSTANCES
            value: "20"
          - name: NODE_REGISTER_CYCLE
            value: "600"
          - name: HUB_PORT_4444_TCP_ADDR
            value: "hub"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
          - name: DBUS_SESSION_BUS_ADDRESS
            value: "/dev/null"
          - name: no_proxy
            value: "localhost"
          - name: HUB_ENV_no_proxy
            value: "localhost"
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: hub
  spec:
    ports:
    - name: 4444-tcp
      port: 4444
      targetPort: 4444
    selector:
      deploymentconfig: selenium-grid
  status:
    loadBalancer: {}

