apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: robot-framework
  spec:
    replicas: 1
    selector:
      deploymentconfig: robot-framework
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: robot-framework
      spec:
        containers:
        - image: innovateuk/robot-framework:1.0-SNAPSHOT
          name: robot-framework
          imagePullPolicy: Always
          resources:
            limits:
              memory: 600M
              cpu: 400m
            requests:
              cpu: 100m
              memory: 400M
          ports: {}
          restartPolicy:
            never: {}
    test: false
    triggers:
    - type: ConfigChange
  status: {}



