options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 0
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-trailing-zero: 0
  no-transition-all: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 0

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  function-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format:
    - 0
    -
      allow-leading-underscore: false

  # Style Guide
  border-zero: 0
  brace-style: 0
  class-name-format: 0
  clean-import-paths: 0
  empty-args: 0
  hex-length: 0
  hex-notation: 0
  indentation:
    - 2
    -
      size: 2
  leading-zero: 0
  nesting-depth: 0
  no-trailing-whitespace: 0
  pseudo-element: 0
  property-sort-order: 0
  quotes: 0
  shorthand-values: 0
  url-quotes: 0
  variable-for-property: 0
  zero-unit: 0

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 0
  space-after-colon: 0
  space-before-brace: 0
  space-before-bang: 0
  space-after-bang: 0
  space-between-parens: 0

  # Final Items
  trailing-semicolon: 0
  final-newline: 0
