apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: production-file-upload-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 20G
  selector:
    matchLabels:
      production: "production"