apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sysint-file-upload-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 20G
  selector:
    matchLabels:
      demo: "sysint"