apiVersion: v1
kind: PersistentVolume
metadata:
  name: production-fileupload-vol
  labels:
    production: production
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20G
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv-production
  persistentVolumeReclaimPolicy: Retain