apiVersion: v1
kind: PersistentVolume
metadata:
  name: production-fileupload-vol
spec:
  metadata:
    labels:
      production: production
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20G
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv-production
  persistentVolumeReclaimPolicy: Retain