apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: idp
  spec:
    replicas: 1
    selector:
      deploymentconfig: idp
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 600
        maxSurge: 2
        maxUnavailable: 0
    template:
      metadata:
        labels:
          deploymentconfig: idp
      spec:
        containers:
        - image: innovateuk/idp-service:1.0-SNAPSHOT
          name: idp
          livenessProbe:
            httpGet:
              path: /idp/status
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /idp/status
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
          imagePullPolicy: Always
          env:
          - name: JAVA_OPTS
            value: -Xms384M -Xmx768M -javaagent:/newrelic.jar
          - name: NEW_RELIC_APP_NAME
            value: "ifs-idp-service (<<NEWRELIC-ENVIRONMENT>>)"
          - name: NEW_RELIC_LICENSE_KEY
            value: "<<NEWRELIC-LICENCE-KEY>>"
          - name: NEW_RELIC_LOG
            value: "STDOUT"
          - name: IDP_PROXY_CERTIFICATE
            value: "<<SSLCERT>>"
          - name: IDP_PROXY_CACERTIFICATE
            value: "<<SSLCACERT>>"
          - name: IDP_PROXY_KEY
            value: "<<SSLKEY>>"
          - name: SP_PROXY_CERTIFICATE
            value: "<<SSLCERT>>"
          - name: SPHOST
            value: <<SHIB-ADDRESS>>
          - name: IDPHOST
            value: <<SHIB-IDP-ADDRESS>>
          - name: HTTPSPORT
            value: "9443"
          - name: HTTPPORT
            value: "9080"
          - name: MEMCACHE_ENDPOINT
            value: "cluster5-memcached01.l8op6o.cfg.euw2.cache.amazonaws.com:11211"
          - name: LDAPURL
            value: "ldap://oldap.org.iuk.local:389"
          - name: LDAPUSESTARTTLS
            value: "false"
          - name: LDAPUSESSL
            value: "false"
          - name: LDAPPORT
            value: "389"
          - name: LDAPBASEDN
            value: "dc=int,dc=g2g3digital,dc=net"
          - name: LDAPBINDDN
            value: "cn=admin,dc=int,dc=g2g3digital,dc=net"
          - name: LDAPBINDDNCRED
            value: "<<LDAP-PASSWORD>>"
          - name: LDAPUSERFILTER
            value: "(&(mail={user})(!(employeeType=inactive)))"
          - name: LDAPRURL
            value: "ldap://oldap.org.iuk.local:389"
          - name: LDAPRBASEDN
            value: "dc=int,dc=g2g3digital,dc=net"
          - name: LDAPRBINDDN
            value: "cn=admin,dc=int,dc=g2g3digital,dc=net"
          - name: LDAPRBINDDNCRED
            value: "<<LDAP-PASSWORD>>"
          - name: LDAPRUSESTARTTLS
            value: "false"
          - name: LDAPRTRUSTCERT
            value: "%{idp.authn.LDAP.trustCertificates:undefined}"
          - name: LDAPRSEARCHFILTER
            value: "(mail=$resolutionContext.principal)"
          - name: LDAPRRETURNATTRIBUTE
            value: "mail,uid"
          - name: LDAPAUTHENTICATOR
            value: "bindSearchAuthenticator"
          - name: GOOGLEANALYTICS_TRACKINGID
            value: "UA-3837161-32"
          ports:
          - containerPort: 9443
          - containerPort: 9080
          resources:
            requests:
              memory: 1024M
            limits:
              memory: 1500M
          test: false
  triggers:
  - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: idp
  spec:
    ports:
    - name: 443-tcp
      port: 443
      targetPort: 9443
    selector:
      deploymentconfig: idp
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Route
  metadata:
    name: idp
  spec:
    host: <<SHIB-IDP-ADDRESS>>
    port:
      targetPort: 443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: idp
